package GUI;
import javax.swing.*;
import java.awt.*;
import Exceptions.*;
import Protein.*;
/**
 *
 * @author Kiro
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        
        //look & feel layout на главната диалога
        ConverterDialog.setResizable(false);
        
        try{
            UIManager.setLookAndFeel
                    ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(ConverterDialog);
           }
        catch(Exception exc)
        {
        }

        //look & feel layout на главната форма
        try{
            UIManager.setLookAndFeel
                    ("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
           }
        catch(Exception exc)
        {
        }

        //radioButtons обединяване в radio buttons group
        ButtonGroup bgroup = new ButtonGroup();
        bgroup.add(model1RadioButton);
        bgroup.add(model2RadioButton);
        bgroup.add(model3RadioButton);
        
        fromButtonGroup.add(fromAlphaRadio);
        fromButtonGroup.add(fromHPRadio);
        fromButtonGroup.add(fromBinRadio);
        fromBinRadio.setSelected(true);
        
        toButtonGroup.add(toHPRadio);
        toButtonGroup.add(toBinRadio);
        toBinRadio.setSelected(true);

        //първото е винаги селектирано по default
        model1RadioButton.setSelected(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConverterDialog = new javax.swing.JDialog();
        convertButton = new javax.swing.JButton();
        toLabel = new javax.swing.JLabel();
        fromAlphaRadio = new javax.swing.JRadioButton();
        fromBinRadio = new javax.swing.JRadioButton();
        fromHPRadio = new javax.swing.JRadioButton();
        fromLabel = new javax.swing.JLabel();
        toHPRadio = new javax.swing.JRadioButton();
        toBinRadio = new javax.swing.JRadioButton();
        convertedTxtField = new javax.swing.JTextField();
        convertTxtField = new javax.swing.JTextField();
        fromButtonGroup = new javax.swing.ButtonGroup();
        toButtonGroup = new javax.swing.ButtonGroup();
        exitButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        model1RadioButton = new javax.swing.JRadioButton();
        model2RadioButton = new javax.swing.JRadioButton();
        model3RadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        twoDmenu = new javax.swing.JMenuItem();
        threeDmenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        convertMenu = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenuItem();

        ConverterDialog.setTitle("Конвертор");
        ConverterDialog.setMinimumSize(new java.awt.Dimension(310, 230));

        convertButton.setText("Конвертирай!");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        toLabel.setText("В:");

        fromAlphaRadio.setText("Алфа формат");

        fromBinRadio.setText("Бинарен формат");

        fromHPRadio.setText("НР формат");

        fromLabel.setText("От:");

        toHPRadio.setText("НР формат");

        toBinRadio.setText("Бинарен формат");

        javax.swing.GroupLayout ConverterDialogLayout = new javax.swing.GroupLayout(ConverterDialog.getContentPane());
        ConverterDialog.getContentPane().setLayout(ConverterDialogLayout);
        ConverterDialogLayout.setHorizontalGroup(
            ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConverterDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(convertedTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(ConverterDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(fromLabel)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConverterDialogLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(convertButton)
                .addGap(10, 10, 10))
            .addGroup(ConverterDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(toLabel)
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(ConverterDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toBinRadio)
                    .addComponent(fromBinRadio))
                .addGroup(ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConverterDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromHPRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromAlphaRadio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConverterDialogLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toHPRadio)
                        .addGap(95, 95, 95)))
                .addContainerGap())
        );
        ConverterDialogLayout.setVerticalGroup(
            ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConverterDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(fromLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromBinRadio)
                    .addComponent(fromHPRadio)
                    .addComponent(fromAlphaRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(convertTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConverterDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toBinRadio)
                    .addComponent(toHPRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertedTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convertButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HP моделиране");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        exitButton.setText("Изход");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        okButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK.png"))); // NOI18N
        okButton.setText("ОК");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        model1RadioButton.setText("модел №: 1");

        model2RadioButton.setText("модел №: 2");

        model3RadioButton.setText("модел №: 3");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/a.png"))); // NOI18N

        jMenu1.setText("Опции");

        twoDmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        twoDmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diagram.png"))); // NOI18N
        twoDmenu.setText("2D визуализация");
        twoDmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoDmenuActionPerformed(evt);
            }
        });
        jMenu1.add(twoDmenu);

        threeDmenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        threeDmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diagram.png"))); // NOI18N
        threeDmenu.setText("3D визуализация");
        threeDmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeDmenuActionPerformed(evt);
            }
        });
        jMenu1.add(threeDmenu);
        jMenu1.add(jSeparator1);

        convertMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        convertMenu.setText("Конвертор");
        convertMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertMenuActionPerformed(evt);
            }
        });
        jMenu1.add(convertMenu);
        jMenu1.add(jSeparator2);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        exitMenu.setText("Изход");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Помощ");

        aboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/About.png"))); // NOI18N
        aboutMenu.setText("За програмата...");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(model2RadioButton)
                            .addComponent(model1RadioButton)
                            .addComponent(model3RadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exitButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(model1RadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model2RadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model3RadioButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        if (model1RadioButton.isSelected()){
            InputProteinForm1 AAF = new InputProteinForm1();

            //затваря текущата форма
            this.dispose();
        
            //Получаване на размера на екрана
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            //Определя новата локация на прозорецът
            int w = AAF.getSize().width;
            int h = AAF.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            // помещава прозорецът
            AAF.setLocation(x, y);
            AAF.setVisible(true);
        }

        else if (model2RadioButton.isSelected()){
            InputProteinForm2 AAF = new InputProteinForm2();

            //затваря текущата форма
            this.dispose();

            //Получаване на размера на екрана
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            // Определя новата локация на прозорецът
            int w = AAF.getSize().width;
            int h = AAF.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            //помещава прозорецът
            AAF.setLocation(x, y);
            AAF.setVisible(true);
        }

        else if (model3RadioButton.isSelected()){
            InputProteinForm3 AAF = new InputProteinForm3();

            //затваря текущата форма
            this.dispose();

            // Получаване на размера на екрана
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            // Определя новата локация на прозорецът
            int w = AAF.getSize().width;
            int h = AAF.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            //помещава прозорецът
            AAF.setLocation(x, y);
            AAF.setVisible(true);
        }  
    }//GEN-LAST:event_okButtonActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void threeDmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeDmenuActionPerformed
            Plotting3DModel ModelForm = new Plotting3DModel();

            //затваря текущата форма
            this.dispose();

            // получава се размерът на екрана
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            // определя новата локация на прозореца
            int w = ModelForm.getSize().width;
            int h = ModelForm.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            // помещава прозорецът
            ModelForm.setLocation(x, y);
            ModelForm.setVisible(true);
    }//GEN-LAST:event_threeDmenuActionPerformed

    private void twoDmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoDmenuActionPerformed
            Plotting2DModel ModelForm = new Plotting2DModel();

            //затваря текущата форма
            this.dispose();

            // получава се размерът на екрана
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            // определя новата локация на прозорецът
            int w = ModelForm.getSize().width;
            int h = ModelForm.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            // помещава прозорецът
            ModelForm.setLocation(x, y);
            ModelForm.setVisible(true);
    }//GEN-LAST:event_twoDmenuActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        new AboutForm();
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void convertMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertMenuActionPerformed
        ConverterDialog.setAlwaysOnTop(true);
        
        //получава се размерът на екрана
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        // определя новата локация на диалога
        int h = ConverterDialog.getSize().height;
        int w = ConverterDialog.getSize().width;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        ConverterDialog.setBounds(x, y, w, h);
        
        ConverterDialog.setVisible(true);
    }//GEN-LAST:event_convertMenuActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        /*
         * fromButtonGroup.add(fromAlphaRadio);
        fromButtonGroup.add(fromHPRadio);
        fromButtonGroup.add(fromBinRadio);
         */
        try{
            if (convertTxtField.getText().isEmpty())
                throw new EmptyFieldException();
        
            if (fromBinRadio.isSelected()==true){
                if (Protein.isCorrectBinary
                            (convertTxtField.getText())==false){
                        throw new BinaryInputException();
                    }
                else{
                    if (toBinRadio.isSelected()==true)
                        convertedTxtField.setText(convertTxtField.getText());
                
                
                    if (toHPRadio.isSelected()==true)
                        convertedTxtField.setText
                                (Protein.ConvertBinaryToHP
                                    (convertTxtField.getText()));   
                }
            }
            
            if (fromHPRadio.isSelected()==true){
                if (Protein.isCorrectHP(convertTxtField.getText())==false){
                    throw new HPInputException();
                }
                
                else{
                    if (toBinRadio.isSelected()==true){
                        convertedTxtField.setText(Protein.ConvertHPtoBinary
                                (convertTxtField.getText()));
                    }
                    
                    if (toHPRadio.isSelected()==true){
                        convertedTxtField.setText(convertTxtField.getText());
                    }
                }
            }
            
            if (fromAlphaRadio.isSelected()==true){
                if (Protein.isCorrect(convertTxtField.getText())==false){
                    throw new AlphaInputException();
                }
                
                else{
                    if (toBinRadio.isSelected()==true){
                        convertedTxtField.setText(Protein.ConvertAlphaToBinary
                                (convertTxtField.getText()));
                    }
                    
                    if (toHPRadio.isSelected()==true){
                        convertedTxtField.setText(Protein.ConvertAlphaToHP
                                (convertTxtField.getText()));
                    }
                }
            }
            
        }
                
        catch (BinaryInputException e){
        }
        
        catch (EmptyFieldException e){    
        }
        
        catch (HPInputException e){  
        }
        
        catch (AlphaInputException e){
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void Main() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ConverterDialog;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JButton convertButton;
    private javax.swing.JMenuItem convertMenu;
    private javax.swing.JTextField convertTxtField;
    private javax.swing.JTextField convertedTxtField;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JRadioButton fromAlphaRadio;
    private javax.swing.JRadioButton fromBinRadio;
    private javax.swing.ButtonGroup fromButtonGroup;
    private javax.swing.JRadioButton fromHPRadio;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JRadioButton model1RadioButton;
    private javax.swing.JRadioButton model2RadioButton;
    private javax.swing.JRadioButton model3RadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JMenuItem threeDmenu;
    private javax.swing.JRadioButton toBinRadio;
    private javax.swing.ButtonGroup toButtonGroup;
    private javax.swing.JRadioButton toHPRadio;
    private javax.swing.JLabel toLabel;
    private javax.swing.JMenuItem twoDmenu;
    // End of variables declaration//GEN-END:variables

}