package GUI;

import javax.swing.*;
import Protein.*;
import java.awt.*;
import Exceptions.*;

public class Plotting3DModel extends javax.swing.JFrame {

    protected int counter = 0;
    protected double [] solution;
    protected String protein;

    /** Creates new form Plotting3DModel */
    public Plotting3DModel() {
        initComponents();

        //нередактируемост на останалите компоненти
        jPanel2.setEnabled(false);
        AddTextField.setEnabled(false);
        AddButton.setEnabled(false);
        jTextArea1.setEnabled(false);
        VisualiseButton.setEnabled(false);
        EditProteinButton.setEnabled(false);
        RemoveButton.setEnabled(false);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProteinTextField = new javax.swing.JTextField();
        AddProteinButton = new javax.swing.JButton();
        EditProteinButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        InsertLabel = new javax.swing.JLabel();
        AddTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        RemoveButton = new javax.swing.JButton();
        VisualiseButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3D визуализация");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Протеин:"));

        AddProteinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/OK.png"))); // NOI18N
        AddProteinButton.setText("ОК");
        AddProteinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProteinButtonActionPerformed(evt);
            }
        });

        EditProteinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        EditProteinButton.setText("Измени");
        EditProteinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProteinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProteinTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddProteinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditProteinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddProteinButton, EditProteinButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ProteinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(AddProteinButton)
                    .addComponent(EditProteinButton))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Стойностти за координатите"));

        InsertLabel.setText("Вмъкни в списъка:");

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Create.png"))); // NOI18N
        AddButton.setText("   Добави");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 11));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        RemoveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Remove.png"))); // NOI18N
        RemoveButton.setText("Премахни");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        VisualiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Diagram.png"))); // NOI18N
        VisualiseButton.setText("Визуализирай");
        VisualiseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualiseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(InsertLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(RemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(VisualiseButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertLabel)
                    .addComponent(AddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RemoveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(VisualiseButton)))
                .addContainerGap())
        );

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        ExitButton.setText("Изход");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(BackButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        //фрейм за диалога
        JFrame frame = new JFrame();
        if (counter == (protein.length()-1)){
            AddButton.setEnabled(false);
            VisualiseButton.setEnabled(true);
        }
        try {
            int Int = Integer.parseInt(AddTextField.getText());
            double Double = (double) Int;
            System.out.println(Double);

            int temp = counter + 1;
            jTextArea1.setText(jTextArea1.getText() + ("x" + Int + "_" +
                                                        temp + "\n"));
            solution[counter] = Double;
            AddTextField.setText(null);
            
            counter++;
        }

         catch (java.lang.NumberFormatException e){
             JOptionPane.showMessageDialog(frame,
                "Въведете целочислени положителни данни!",
                "Грешка във въведените данни",
                JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_AddButtonActionPerformed

    private void AddProteinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProteinButtonActionPerformed
        //проверява дали въведеният протеин съдържа хидрофобни стойности
        try{
            if(Protein.CountH(ProteinTextField.getText())==0)
                throw new NoHException();
        }
        catch(NoHException e){
        }

        //фрейм за диалога
        JFrame frame = new JFrame();

        try{
            for (int i=0; i<ProteinTextField.getText().length(); i++){
                if ( !(ProteinTextField.getText().charAt(i)=='1')
                    && !(ProteinTextField.getText().charAt(i)=='0'))
                    throw new BinaryInputException();
            }

            if (ProteinTextField.getText() == null ? "" == null :
                ProteinTextField.getText().equals(""))
                throw new EmptyFieldException();
            //инициализация на протеина; задаване на дължината на масива
            //с решенията
            protein = ProteinTextField.getText();
            solution = new double [protein.length()];
            counter = 0;

            //редактируемост на останалите компоненти
            jPanel2.setEnabled(true);
            AddTextField.setEnabled(true);
            AddButton.setEnabled(true);
            jTextArea1.setEnabled(true);
            VisualiseButton.setEnabled(false);
            EditProteinButton.setEnabled(true);
            AddProteinButton.setEnabled(false);
            ProteinTextField.setEditable(false);
            RemoveButton.setEnabled(true);
            
        }

        catch(BinaryInputException e){
        }

        catch(EmptyFieldException e){
        }
    }//GEN-LAST:event_AddProteinButtonActionPerformed

    private void EditProteinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProteinButtonActionPerformed
        //нередактируемост на останалите компоненти
        jPanel2.setEnabled(false);
        AddTextField.setEnabled(false);
        AddButton.setEnabled(false);
        jTextArea1.setEnabled(false);
        VisualiseButton.setEnabled(false);
        EditProteinButton.setEnabled(false);
        AddProteinButton.setEnabled(true);
        ProteinTextField.setEditable(true);
        RemoveButton.setEnabled(false);
        jTextArea1.setText("");
    }//GEN-LAST:event_EditProteinButtonActionPerformed

    private void VisualiseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualiseButtonActionPerformed
        for (int i=0; i<solution.length; i++)
            System.out.print(solution[i] + " ");
        Protein.Ploting3D(solution,protein);
    }//GEN-LAST:event_VisualiseButtonActionPerformed

    /*
     * param@ modify - стринг в който се запазва стойността от последния
                       елемент на стека
     * param@ temp - целочислената стойност от последния елемент на стека
     */
    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed

        try{
            //инициализация на modify и temp
            String modify;
            int temp = (int) solution[counter-1];
            modify = "x" + temp + "_" + counter +"\n";

            //махане на предишния член
            System.out.println(modify);
            jTextArea1.setText(jTextArea1.getText().replace(modify, ""));
            counter--;

            //проверка за бутона за визуализация
            if (counter != (protein.length())){
                VisualiseButton.setEnabled(false);
                AddButton.setEnabled(true);
            }
        }

        catch (java.lang.ArrayIndexOutOfBoundsException e){
            //фрейм за диалога
            JFrame frame = new JFrame();
            
            JOptionPane.showMessageDialog(frame, "Стека е празен!", "Грешка",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MainForm MF = new MainForm();

            //затваря текущата форма
            this.dispose();

            // Get the size of the screen
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

            // Determine the new location of the window
            int w = MF.getSize().width;
            int h = MF.getSize().height;
            int x = (dim.width-w)/2;
            int y = (dim.height-h)/2;

            // Move the window
            MF.setLocation(x, y);
            MF.setVisible(true);

            jTextArea1.setEditable(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton AddProteinButton;
    private javax.swing.JTextField AddTextField;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton EditProteinButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel InsertLabel;
    private javax.swing.JTextField ProteinTextField;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JButton VisualiseButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}